books_app/models.py
"""Create database models to represent tables."""
from books_app.extensions import db
from sqlalchemy.orm import backref
from flask_login import UserMixin
import enum

class FormEnum(enum.Enum):
    """Helper class to make it easier to use enums with forms."""
    @classmethod
    def choices(cls):
        return [(choice.name, choice) for choice in cls]

    def __str__(self):
        return str(self.value)

class Audience(FormEnum):
    CHILDREN = 'Children'
    YOUNG_ADULT = 'Young Adult'
    ADULT = 'Adult'
    ALL = 'All'

class Book(db.Model):
    """Book model."""
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), nullable=False)
    publish_date = db.Column(db.Date)

    # The author - Who wrote it?
    author_id = db.Column(db.Integer, db.ForeignKey('author.id'), nullable=False)
    author = db.relationship('Author', back_populates='books')
    
    # The audience - Who is this book written for?
    audience = db.Column(db.Enum(Audience), default=Audience.ALL)

    # The genres, e.g. fiction, sci-fi, fantasy
    genres = db.relationship(
        'Genre', secondary='book_genre', back_populates='books')

    # Who favorited this book?
    users_who_favorited = db.relationship(
        'User', secondary='user_book', back_populates='favorite_books')

    def __str__(self):
        return f'<Book: {self.title}>'

    def __repr__(self):
        return f'<Book: {self.title}>'

class Author(db.Model):
    """Author model."""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    biography = db.Column(db.String(200))
    books = db.relationship('Book', back_populates='author')

    def __str__(self):
        return f'<Author: {self.name}>'

    def __repr__(self):
        return f'<Author: {self.name}>'

class Genre(db.Model):
    """Genre model."""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False, unique=True)
    books = db.relationship(
        'Book', secondary='book_genre', back_populates='genres')

    def __str__(self):
        return f'<Genre: {self.name}>'

    def __repr__(self):
        return f'<Genre: {self.name}>'

book_genre_table = db.Table('book_genre',
    db.Column('book_id', db.Integer, db.ForeignKey('book.id')),
    db.Column('genre_id', db.Integer, db.ForeignKey('genre.id'))
)

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)
    favorite_books = db.relationship(
        'Book', secondary='user_book', back_populates='users_who_favorited')

    def __repr__(self):
        return f'<User: {self.username}>'

favorite_books_table = db.Table('user_book',
    db.Column('book_id', db.Integer, db.ForeignKey('book.id')),
    db.Column('user_id', db.Integer, db.ForeignKey('user.id'))
)

books_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, DateField, SelectField, SubmitField, TextAreaField
from wtforms.ext.sqlalchemy.fields import QuerySelectField, QuerySelectMultipleField
from wtforms.validators import DataRequired, Length, ValidationError
from books_app.models import Audience, Book, Author, Genre, User

class BookForm(FlaskForm):
    """Form to create a book."""
    title = StringField('Book Title',
        validators=[DataRequired(), Length(min=3, max=80)])
    publish_date = DateField('Date Published')
    author = QuerySelectField('Author',
        query_factory=lambda: Author.query, allow_blank=False)
    audience = SelectField('Audience', choices=Audience.choices())
    genres = QuerySelectMultipleField('Genres',
        query_factory=lambda: Genre.query)
    submit = SubmitField('Submit')


class AuthorForm(FlaskForm):
    """Form to create an author."""
    name = StringField('Author Name',
        validators=[DataRequired(), Length(min=3, max=80)])
    biography = TextAreaField('Author Biography')
    submit = SubmitField('Submit')


class GenreForm(FlaskForm):
    """Form to create a genre."""
    name = StringField('Genre Name',
        validators=[DataRequired(), Length(min=3, max=80)])
    submit = SubmitField('Submit')

books_app/main/routes.py
"""Import packages and modules."""
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime
from books_app.models import Book, Author, Genre, User
from books_app.main.forms import BookForm, AuthorForm, GenreForm

# Import app and db from events_app package so that we can run app
from books_app.extensions import app, db, bcrypt

main = Blueprint("main", __name__)

##########################################
#           Routes                       #
##########################################


@main.route('/')
def homepage():
    all_books = Book.query.all()
    all_users = User.query.all()
    return render_template('home.html',
        all_books=all_books, all_users=all_users)


@main.route('/create_book', methods=['GET', 'POST'])
@login_required
def create_book():
    form = BookForm()

    # if form was submitted and contained no errors
    if form.validate_on_submit(): 
        new_book = Book(
            title=form.title.data,
            publish_date=form.publish_date.data,
            author=form.author.data,
            audience=form.audience.data,
            genres=form.genres.data
        )
        db.session.add(new_book)
        db.session.commit()

        flash('New book was created successfully.')
        return redirect(url_for('main.book_detail', book_id=new_book.id))
    return render_template('create_book.html', form=form)


@main.route('/create_author', methods=['GET', 'POST'])
@login_required
def create_author():
    form = AuthorForm()
    if form.validate_on_submit():
        new_author = Author(
            name=form.name.data,
            biography=form.biography.data
        )
        db.session.add(new_author)
        db.session.commit()

        flash('New author created successfully.')
        return redirect(url_for('main.homepage'))
    
    # if form was not valid, or was not submitted yet
    return render_template('create_author.html', form=form)


@main.route('/create_genre', methods=['GET', 'POST'])
@login_required
def create_genre():
    form = GenreForm()
    if form.validate_on_submit():
        new_genre = Genre(
            name=form.name.data
        )
        db.session.add(new_genre)
        db.session.commit()

        flash('New genre created successfully.')
        return redirect(url_for('main.homepage'))
    
    # if form was not valid, or was not submitted yet
    return render_template('create_genre.html', form=form)


@main.route('/book/<book_id>', methods=['GET', 'POST'])
def book_detail(book_id):
    book = Book.query.get(book_id)
    form = BookForm(obj=book)
    
    # if form was submitted and contained no errors
    if form.validate_on_submit():
        book.title = form.title.data
        book.publish_date = form.publish_date.data
        book.author = form.author.data
        book.audience = form.audience.data
        book.genres = form.genres.data

        db.session.commit()

        flash('Book was updated successfully.')
        return redirect(url_for('main.book_detail', book_id=book_id))

    return render_template('book_detail.html', book=book, form=form)


@main.route('/profile/<username>')
def profile(username):
    user = User.query.filter_by(username=username).one()
    return render_template('profile.html', user=user)


@main.route('/favorite/<book_id>', methods=['POST'])
@login_required
def favorite_book(book_id):
    book = Book.query.get(book_id)
    if book in current_user.favorite_books:
        flash('Book already in favorites.')
    else:
        current_user.favorite_books.append(book)
        db.session.add(current_user)
        db.session.commit()
        flash('Book added to favorites.')
    return redirect(url_for('main.book_detail', book_id=book_id))


@main.route('/unfavorite/<book_id>', methods=['POST'])
@login_required
def unfavorite_book(book_id):
    book = Book.query.get(book_id)
    if book not in current_user.favorite_books:
        flash('Book not in favorites.')
    else:
        current_user.favorite_books.remove(book)
        db.session.add(current_user)
        db.session.commit()
        flash('Book removed from favorites.')
    return redirect(url_for('main.book_detail', book_id=book_id))

books_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Grocery Store Tracker</title>
        <link rel="stylesheet" href="/static/style.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            <nav>
                <a href="/">Home</a>
                <div>
                    {% if current_user.is_authenticated %}
                    <a href="/create_book">Create Book</a>
                    <a href="/create_author">Create Author</a>
                    <a href="/create_genre">Create Genre</a>
                    <a href="/logout">Log Out</a>
                    {% else %}
                    <a href="/signup">Sign Up</a>
                    <a href="/login">Log In</a>
                    {% endif %}
                </div>
            </nav>

            {% if current_user.is_authenticated %}
            <p>You are logged in as {{ current_user.username }}</p>
            {% endif %}

            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}

            {% block content %}{% endblock %}
        </div>
    </body>
</html>

books_app/templates/book_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ book.title }}</h1>

{% if current_user.is_authenticated %}
    {% if book not in current_user.favorite_books %}
    <form action="/favorite/{{ book.id }}" method="POST">
        <input type="submit" value="Favorite This Book">
    </form>
    {% else %}
    <form action="/unfavorite/{{ book.id }}" method="POST">
        <input type="submit" value="Unfavorite This Book">
    </form>
    {% endif %}
{% endif %}

<p>
    <strong>Author</strong>: {{ book.author.name }}
</p>

<p>
    <strong>Author Bio</strong>: {{ book.author.biography }}
</p>

{% if book.publish_date %}
<p>
    <strong>Publish date</strong>: {{ book.publish_date.strftime('%B %d, %Y') }}
</p>
{% endif %}

<p>
    <strong>Audience</strong>: {{ book.audience }}
</p>

<p>
    <strong>Genres</strong>: 
    
    {% for genre in book.genres %}
    {{ genre.name }},
    {% endfor %}
</p>

<form method="POST" action="{{ url_for('main.book_detail', book_id=book.id) }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Edit this book</legend>

        {{ form.title.label }}
        {{ form.title }}
        
        {{ form.publish_date.label }}
        {{ form.publish_date(placeholder="YYYY-mm-dd") }}
        
        {{ form.author.label }}
        {{ form.author }}
        
        {{ form.audience.label }}
        {{ form.audience }}
        
        {{ form.genres.label }}
        {{ form.genres }}
            
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

books_app/templates/create_author.html
{% extends 'base.html' %}

{% block content %}

<p>Author creation form.</p>

<form method="POST" action="{{ url_for('main.create_author') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter an author</legend>

        {{ form.name.label }}
        {{ form.name }}
        <ul>
        {% for error in form.name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.biography.label }}
        {{ form.biography }}
        <ul>
        {% for error in form.biography.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
            
        {{ form.submit }}
    </fieldset>
</form>


{% endblock %}

books_app/templates/create_book.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{ url_for('main.create_book') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter a book</legend>

        {{ form.title.label }}
        {{ form.title }}
        <ul>
        {% for error in form.title.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.publish_date.label }}
        {{ form.publish_date(placeholder="YYYY-mm-dd") }}
        <ul>
        {% for error in form.title.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.author.label }}
        {{ form.author }}
        <ul>
        {% for error in form.author.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.audience.label }}
        {{ form.audience }}
        <ul>
        {% for error in form.audience.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.genres.label }}
        {{ form.genres }}
        <ul>
        {% for error in form.genres.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
            
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

books_app/templates/create_genre.html
{% extends 'base.html' %}

{% block content %}

<p>Genre creation form.</p>

<form method="POST" action="{{ url_for('main.create_genre') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter a genre</legend>

        {{ form.name.label }}
        {{ form.name }}
        <ul>
        {% for error in form.name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>
        
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

books_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h2>Books</h2>

<ul>
{% for book in all_books %}
    <li><a href="/book/{{ book.id }}">{{ book.title }}</a> by {{ book.author.name }}</li>
{% endfor %}
</ul>

<h2>Users</h2>

<p>
    <a href="/create_user">+ New User</a>
</p>

<ul>
    {% for user in all_users %}
        <li><a href="/profile/{{ user.username }}">{{ user.username }}</a></li>
    {% endfor %}
</ul>



{% endblock %}

books_app/templates/login.html
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

books_app/templates/profile.html
{% extends 'base.html' %}

{% block content %}

<p>
Welcome to {{ user.username }}'s profile.
</p>

<!-- TODO: Display the user's actual favorites here -->

<p>
    {{ user.username }}'s favorite books are:

    <ul>
        {% for book in user.favorite_books %}
        <li><a href="/book/{{ book.id }}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
</p>

{% endblock %}

books_app/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}

    </fieldset>
</form>

{% endblock %}